### ISSUE TITLE
Crash when add date Transaction

### ISSUE THREAD

**Issue by nykroy** [sebastienbarbier/seven23#27]
When i try to add date transaction the app go to empty windows. The way to add date is click on the input and write only simple date format without time.

![imagen](https://user-images.githubusercontent.com/7745881/74000305-da3b4d00-4967-11ea-80ed-d69ce21a37a9.png)

**Comment by sebastienbarbier** [comment]
Bug has been identified before and **fixed in latest version**. You can test on [app.seven23.io](app.seven23.io) if bug also existe in latest version, and if not you need to update your application.

This was due to an update of the library `@date-io/moment` from `1.3.11` to `2.0.1` and fixed on Jan 29, 2020 with [commit 5cc9c7d84da35cd86b4c1a1762d1faa9047e4f96 ](https://github.com/sebastienbarbier/seven23/commit/5cc9c7d84da35cd86b4c1a1762d1faa9047e4f96)

**Comment by nykroy** [comment]
I tried with app.seven23.io and my own seven23 server and failed :(

**Comment by sebastienbarbier** [comment]
Raaah there is may small issues which all together make all of this messy 😭, so sorry.

I received a bug report from app.seven23.io, seams like you run an old version from before the bug. I guess the service worker did not catch the update and can confirm I also had that issue few times. Will need to fix that properly and create an issue.

Can you try to go click on  **Settings** > **About the App** > **Force reload** ? You should then have a popup with latest version available.

**Comment by sebastienbarbier** [comment]
I created an issue (#28) about fixing the update workflow which is not clear for now. Hopefully this might help.

**Comment by nykroy** [comment]
doing reload work perfect!! thank you!!
